services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://db:27017/rag
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Pass the OpenAI API key from environment variables
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
